CitasChernobyl/Models/Admin.cs
namespace CitasChernobyl.Models
{
    public class Admin
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

CitasChernobyl/Models/ErrorViewModel.cs
namespace CitasChernobyl.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CitasChernobyl/Models/Usuario.cs
namespace CitasChernobyl.Models
{
    public class Usuario
    {

        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }

        public string[] Roles { get; set; }

    }
}

CitasChernobyl/Controllers/AccesoController.cs
using CitasChernobyl.Data;
using CitasChernobyl.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CitasChernobyl.Controllers
{
    public class AccesoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Index(Usuario _usuario)
        {
            DA_Usuario _da_usuario = new DA_Usuario();

            var usuario = _da_usuario.ValidarUsuario(_usuario.Correo, _usuario.Clave);

            if (usuario != null)
            {

                //CONFIGURACION DE LA AUTENTICACION
                #region AUTENTICACTION
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.Nombre),
                    new Claim("Correo", usuario.Correo),
                };
                foreach (string rol in usuario.Roles)
                {
                    claims.Add(new Claim(ClaimTypes.Role, rol));
                }
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                #endregion
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }

        }

        public async Task<IActionResult> Salir()
        {
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Index", "login");
        }
    }

}

CitasChernobyl/Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CitasChernobyl.Controllers
{
    public class AdminController : Controller
    {
        // GET: AdminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CitasChernobyl/Controllers/HomeController.cs
using CitasChernobyl.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

using Microsoft.AspNetCore.Authorization;

namespace CitasChernobyl.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize(Roles = "Administrador,Empleado,Cliente")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Citas()
        {
            return View();
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Clientes()
        {
            return View();
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Empleados()
        {
            return View();
        }
        [Authorize(Roles = "Administrador")]
        public IActionResult Informes()
        {
            return View();
        }
        [Authorize(Roles = "Cliente")]
        public IActionResult Perfil_Cliente ()
        {
            return View();
        }
        [Authorize(Roles = "Cliente")]
        public IActionResult Agendar_Cita()
        {
            return View();
        }
        [Authorize(Roles = "Cliente")]
        public IActionResult Historial_Servicios()
        {
            return View();
        }

       

        [Authorize(Roles = "Empleado")]
        public IActionResult Consultar_Agenda()
        {
            return View();
        }

       

        public IActionResult Salir()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CitasChernobyl/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace CitasChernobyl.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CitasChernobyl/Controllers/RegistroController.cs
using Microsoft.AspNetCore.Mvc;

namespace CitasChernobyl.Controllers
{
    public class RegistroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CitasChernobyl/Controllers/SesionFinalizadaController.cs
using Microsoft.AspNetCore.Mvc;

namespace CitasChernobyl.Controllers
{
    public class SesionFinalizadaController : Controller
    {
        public IActionResult SesionFinalizada()
        {
            return View();
        }
    }
}

CitasChernobyl/Views/Acceso/Index.cshtml
@model Usuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Chernobyl BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasChernobyl.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />

</head>

<body>
      <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index"><img src="../image/logo1.png" class="img-fluid logo" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a alingn="right" class="nav-link btnA" asp-area="" asp-controller="Registro" asp-action="Index">Registrate</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="text-center">
                <img src="../image/titularIndex.png" class="img-fluid" style="width:300px ;" alt="">

            </div>
            <div class="row mt-5">
        <div class="col-md-5 mx-auto">
            <form asp-controller="Acceso" asp-action="Index" method="post">
                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="email" class="form-control" asp-for="Correo" placeholder="Email"> 
                </div>

                <!-- Password input -->
                <div class="form-outline mb-4">
                    <input type="password" class="form-control" asp-for="Clave" placeholder="Contraseña"> 
                </div>

                <!-- 2 column grid layout for inline styling -->
                <div class="row mb-4">
                    <div class="col d-flex justify-content-center colorWt">
                        <!-- Checkbox -->
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="form2Example34" checked />
                            <label class="form-check-label" for="form2Example34"> Recuerdame </label>
                        </div>
                    </div>

                    <div class="col colorWt">
                        <!-- Simple link -->
                        <a href="#!">Olvido su Contraseña?</a>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-md-6 mx-auto">
                        <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4 mx-auto btnA">Iniciar Sesión</button>
                    </div>
                </div>

                

            </form>
        </div>

    </div>
        </main>
    </div>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/gsap/gsap.min.js" asp-append-version="true"></script>

</body>

</html>

CitasChernobyl/Views/Home/Agendar_Cita.cshtml
@{
    ViewData["Title"] = "Agendar_Cita";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Agendar Cita</h1>

CitasChernobyl/Views/Home/Citas.cshtml
@{
    ViewData["Title"] = "Citas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Citas</h1>

CitasChernobyl/Views/Home/Clientes.cshtml
@{
    ViewData["Title"] = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="boxDashboard p-4">

    @* fila 2 *@
    <div class="row justify-content-between  mt-3">

        <div class="col-md-12 d-flex align-items-stretch">
            <div class="card p-4 w-100">
                <h2 class="tituloCard">Listado de
                    <strong>Clientes</strong>
                </h2>
                <hr>
                <div class="listProgram">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Fecha ingreso</th>
                                <th scope="col">Número de servicios</th>
                                <th scope="col">Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td> Juan Carlos Torres</td>
                                <td><span><i class="bi bi-calendar3"></i> </span> Lunes 21 Febrero</td>
                                <td><span><i class="bi bi-ticket-perforated-fill"></i></span> 30 servicios</td>
                                <td> <span class="activo"><i class="bi bi-check-square-fill"></i> Activo</span></td>
                                
                            </tr>

                        </tbody>
                    </table>
                </div>

            </div>
        </div>

    


    </div>
    @* fin fila 2 *@
</div>

CitasChernobyl/Views/Home/Empleados.cshtml
@{
    ViewData["Title"] = "Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="boxDashboard p-4">

    @* fila 2 *@
    <div class="row justify-content-between  mt-3">

        <div class="col-md-12 d-flex align-items-stretch">
            <div class="card p-4 w-100">
                <h2 class="tituloCard">Listado de
                    <strong>Empleados</strong>
                </h2>
                <hr>
                <div class="listProgram">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Experiencia</th>
                                <th scope="col">Número de servicios</th>
                                <th scope="col">Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td> Esteban Ortiz</td>
                                <td><span><i class="bi bi-calendar3"></i> </span>3 años</td>
                                <td><span><i class="bi bi-ticket-perforated-fill"></i></span> 300 servicios</td>
                                <td> <span class="activo"><i class="bi bi-check-square-fill"></i> Activo</span></td>
                                
                            </tr>

                        </tbody>
                    </table>
                </div>

            </div>
        </div>

    


    </div>
    @* fin fila 2 *@
</div>

CitasChernobyl/Views/Home/Salir.cshtml
@{
    ViewData["Title"] = "Salir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Salir</h1>

CitasChernobyl/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Identity
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Chernobyl BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasChernobyl.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index"><img src="../image/logo1.png" class="img-fluid logo" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a alingn="right" class="nav-link btnA" asp-area="" asp-controller="Registro" asp-action="Index">Registrate</a>
                        </li>
                        <li class="nav-item">
                            <a alingn="right" class="nav-link btnB" asp-area="" asp-controller="Acceso" asp-action="Index">Iniciar Sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 mx-auto">
                       <div class="boxTitular">
                        <img src="../image/gota.png" class="img-fluid gota" alt="">
                        <img src="../image/titularIndex.png" class="img-fluid" alt="">
                        <img src="../image/1.png" class="img-fluid avatar" alt="">
                       </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 mx-auto">
                        <ul class="boxContIntem">
                            <li>
                                <div class="boxItem">
                                    <figure>
                                        <img src="../image/men1.png" class="imgMen" alt="">
                                    </figure>
                                    <div class="boxItemShape"></div>
                                </div>
                            </li>
                             <li>
                                <div class="boxItem">
                                    <figure>
                                        <img src="../image/men2.png" class="imgMen" alt="">
                                    </figure>
                                    <div class="boxItemShape"></div>
                                </div>
                            </li>
                             <li>
                                <div class="boxItem">
                                    <figure>
                                        <img src="../image/men3.png" class="imgMen" alt="">
                                    </figure>
                                    <div class="boxItemShape"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/gsap/gsap.min.js" asp-append-version="true"></script>
</body>
</html>

CitasChernobyl/Views/Registro/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Chernobyl BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasChernobyl.styles.css" asp-append-version="true" />
</head>
<body>
       <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index"><img src="../image/logo1.png" class="img-fluid logo" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                      
                        <li class="nav-item">
                            <a alingn="right" class="nav-link btnB" asp-area="" asp-controller="Acceso" asp-action="Index">Iniciar Sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        <div class="container">
            <main role="main" class="pb-3">
    <div class="text-center">
        <img src="../image/titularIndex.png" class="img-fluid" style="width:300px ;" alt="">

    </div>
            </main>
        </div>
    <div class="container">
        <div class="row mt-5">
        <div class="col-sm-4 offset-sm-4">

            <form>
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row mb-4">
                    <div class="col">
                        <div class="form-outline">
                            <input type="text" id="form3Example1" class="form-control"  placeholder="Nombre"/> 
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-outline">
                            <input type="text" id="form3Example2" class="form-control" placeholder="Apellido" />
                        </div>
                    </div>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="email" id="form3Example3" class="form-control"  placeholder="Email"/>
                </div>

                <!-- Password input -->
                <div class="form-outline mb-4">
                    <input type="password" id="form3Example4" class="form-control"  placeholder="Contraseña"/>
                </div>

                @* <!-- Checkbox -->
                <div class="form-check d-flex justify-content-center mb-4">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                    <label class="form-check-label" for="form2Example33">
                        Subscribete a nuestro Boletin
                    </label>
                </div> *@
                  <div class="row">
                    <div class="col-md-7 mx-auto">
                        <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4 mx-auto btnA">Crear Cuenta</button>
                    </div>
                </div>
                <!-- Submit button -->
                

             
            </form>


        </div>

         </div>  
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="~/lib/gsap/gsap.min.js" asp-append-version="true"></script>

</body>
</html>

CitasChernobyl/Views/SesionFinalizada/SesionFinalizada.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SesionFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasChernobyl.styles.css" asp-append-version="true" />
</head>
<body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">Chernobyl BarberShop</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 justify-content-end">
                            <li class="nav-item">
                                <a alingn="right" class="nav-link text-dark" asp-area="" asp-controller="Registro" asp-action="Index">Registrate</a>
                            </li>
                            <li class="nav-item">
                                <a alingn="right" class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Index">Iniciar Sesión</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    <div class="text-center">
        <h1 class="display-4">Sesión Finalizada</h1>

    </div>
        <div class="container">
            <main role="main" class="pb-3">
            </main>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </body>
</html>

CitasChernobyl/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Chernobyl BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/global.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasChernobyl.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navBarInner">
            <div class="container-fluid">
                 <a class="navbar-brand innerBrand" asp-area="" asp-controller="Home" asp-action="Index"><img src="../image/logo1.png" class="img-fluid logo" alt=""></a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navList">
                    
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                        @if (User.IsInRole("Administrador"))
                        {   
                      
                            @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Citas">Citas</a>
                            </li>*@
                            <li class="nav-item">
                                
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Clientes">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Empleados">Empleados</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Informes">Informes</a>
                            </li>

                        }
                        
                        @if (User.IsInRole("Cliente"))
                        {   
                     
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Perfil_Cliente">Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Agendar_Cita">Agendar Cita</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Historial_Servicios">Historial Servicios</a>
                            </li>
                        }

                        @if (User.IsInRole("Empleado"))
                        {
                          
                       
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Consultar_Agenda">Consultar Agenda</a>
                            </li>
                        }

                        <li class="nav-item outBtn">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Cerrar Sesión</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container contInner">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted footerInner">
        <div class="container">
            &copy; 2022 - CitasChernobyl - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="~/lib/gsap/gsap.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>